name: CI/CD Pipeline for Node.js Application Deployment

on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Format Terraform
      run: terraform fmt
      working-directory: ./terraform-files

    - name: Initialize Terraform
      run: terraform init
      working-directory: ./terraform-files

    - name: Plan Terraform
      run: terraform plan
      working-directory: ./terraform-files

    - name: Apply Terraform
      run: terraform apply -auto-approve
      working-directory: ./terraform-files

  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: Set up Node.js
  #     uses: actions/setup-node@v2
  #     with:
  #       node-version: '14'

  #   - name: Installing requirements
  #     run: npm install

  #   - name: Running tests
  #     run: npm test

  #   - name: Upload artifact for deployment job
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: node-app
  #       path: .

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #   - name: Download artifact from build job
  #     uses: actions/download-artifact@v3
  #     with:
  #       name: node-app

  #   - name: Deploy to Azure Web App
  #     id: deploy-to-webapp
  #     uses: azure/webapps-deploy@v2
  #     with:
  #       app-name: 'webapp7216'
  #       slot-name: 'staging'
  #       publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  #       package: .
